[package]
name = "iocp_ring_reader"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = { version = "0.59", features = [
  "Win32_System_IO",
  "Win32_Security",
  "Win32_Foundation",
  "Win32_Storage_FileSystem",
  "Win32_System_Threading",
  "Win32_System_Memory"
] }